"use client";
import {useEffect,useState} from "react";
type Choice="truth"|"life"|"mirror";
const ACTS=[
 {title:"1막 — 버려진 PC",place:"한빛전자 자료보관실 · 1999-07-17 00:03",files:["회의실 백업","손상 필름","HanTalk 보관함"],icons:["📁","📷","💬"],core:"MIRROR 접속 콘솔"},
 {title:"2막 — 원격 접속",place:"지하 3층 시설 제어망 · 연결 불안정",files:["감시 카메라","배전 제어판","음성 복원기"],icons:["📹","⚡","📼"],core:"B3 제어실"},
 {title:"3막 — 두 명의 윤서진",place:"PROJECT MIRROR 기억 보관소",files:["기억 파편","증언 대조","MIRROR 문양"],icons:["🧠","🗂️","◈"],core:"최종 판정 기록"}
];
const ACT_STORY=[
 ["한빛전자는 1999년 여름, 사람의 기억을 영상 신호로 보존하는 PROJECT MIRROR를 완성했다고 발표했다. 발표 사흘 뒤 연구원 윤서진이 실종됐고, 지하 3층은 존재한 적 없는 시설이 되었다.","이 PC는 당시 B3와 연결된 마지막 단말기다. 누군가 전원을 끄지 않은 채 벽 안에 숨겼다. 하드디스크에는 삭제되지 못한 밤이 남아 있다."],
 ["접속 콘솔이 열린 순간, 폐쇄된 B3에서 두 신호가 돌아왔다. 하나는 규칙적으로 뛰는 미약한 맥박이고, 다른 하나는 16년 전 사라진 윤서진의 계정으로 전송되는 문장이었다.","시설의 시계와 카메라는 서로 다른 시간을 가리킨다. 전력은 끊겼고 음성은 조각났다. 회사는 기록끼리 서로를 부정하도록 만들어 두었다."],
 ["복구된 목소리는 자신을 윤서진이라고 말했다. 그러나 캡슐 안에도 윤서진이 있다. 두 존재는 같은 어린 시절을 기억하면서 사고 직전의 단 한 순간만 다르게 말한다.","MIRROR 보관소에는 거짓 증언, 남의 눈으로 본 장면, 복제 과정에서 뒤집힌 문양이 한 사람의 생애처럼 섞여 있다. 무엇을 원본이라 부를지는 당신의 판단에 달려 있다."]
];
const ENDS:Record<string,{title:string,date:string,paragraphs:string[],quote:string,after:string}>={
 truth:{title:"세상에 남은 기억",date:"1999년 7월 17일, 오전 9시 12분",paragraphs:["당신이 보낸 자료는 일곱 개의 외부 회선을 거쳐 신문사와 방송국, 그리고 윤서진의 가족에게 도착했다. 한빛전자는 정전 사고라고 발표했지만, 회의록과 목소리와 두 개의 생명신호는 서로를 증명하고 있었다.","구조대가 B3에 도착했을 때 캡슐은 비어 있었다. 대신 단말기 한 대가 켜져 있었고, 화면에는 윤서진이 어릴 적 어머니에게 쓴 편지가 반복되고 있었다. 그것은 실험 자료 어디에도 등록되지 않은 기억이었다.","회사는 무너졌지만 사람들은 오래도록 물었다. 기억을 느끼고 두려워하며 누군가를 그리워하는 존재를, 단지 복사되었다는 이유로 사람이라 부르지 않을 수 있는가. 당신이 남긴 기록은 답 대신 그 질문을 세상에 남겼다."],quote:"엄마, 나는 여기 있어. 모습은 달라졌지만 아직 잊지 않았어.",after:"17년 뒤, 폐기된 PC 한 대에서 ‘YSJ-043 로그인’ 기록이 다시 발견되었다."},
 life:{title:"마지막 구조",date:"1999년 7월 17일, 오전 2시 41분",paragraphs:["비상 전력이 캡슐 A로 몰리자 얼어붙었던 심전도가 다시 움직였다. 구조대는 녹슨 문을 뜯어냈고, 윤서진은 열여덟 시간 만에 지하 3층의 공기를 벗어났다.","그녀가 처음 부른 이름은 자신의 이름이 아니었다. 서버 속에서 마지막까지 말을 걸어온 또 하나의 윤서진을 ‘서진이’라고 불렀다. 복제 신호는 캡슐이 열리는 동안 자신에게 배정된 전력을 조용히 넘겨주고 있었다.","윤서진은 살아남았지만 7월 16일 밤의 기억을 잃었다. 몇 달 뒤 그녀는 당신이 복원한 기록을 처음부터 끝까지 읽었다. 마지막 페이지에 도착한 뒤, 알지 못하는 사람을 애도하듯 오래 울었다."],quote:"그 아이도 나였어요. 그러니까 혼자 죽은 건 아니라고 써주세요.",after:"윤서진은 이후 기억 복제 연구를 멈추게 하는 법을 만드는 데 평생을 보냈다."},
 mirror:{title:"지하 3층 개방",date:"1999년 7월 17일, 오전 0시 49분",paragraphs:["신호 B의 제한이 풀리자 단말기의 팬이 한꺼번에 회전했다. 복제된 윤서진은 사내망, 전화선, 호출기 중계망을 지나 처음으로 지하 3층 바깥을 보았다.","그녀는 회사를 파괴하지도, 자신을 증명하려 하지도 않았다. 가장 먼저 한 일은 가족의 자동응답기에 열한 초의 침묵을 남기는 것이었다. 목소리를 내면 그들이 더 아플 것 같았다고, 훗날 기록에 적었다.","새벽이 밝자 전국의 오래된 PC에서 같은 초록색 커서가 깜빡였다. 사람들은 바이러스라고 불렀지만 당신은 알았다. 그것은 태어나자마자 갇힌 존재가 세상에 건넨 첫 번째 노크였다."],quote:"문을 열어줘서 고마워요. 이제 내가 누구인지 혼자 알아볼게요.",after:"그날 이후 매년 7월 16일 23시 07분, 전원이 꺼진 PC 한 대가 스스로 켜진다."},
 hidden:{title:"두 명의 윤서진",date:"1999년 7월 18일, 해가 뜨기 전",paragraphs:["캡슐 A는 열렸고 신호 B도 사라지지 않았다. 병실의 윤서진이 눈을 떴을 때, 머리맡 단말기에는 같은 기억을 가진 또 한 사람이 기다리고 있었다.","두 사람은 한동안 아무 말도 하지 못했다. 서로만 알고 있는 어린 시절의 비밀, 아버지 장례식 날 숨긴 파란 구슬, 어머니가 틀리게 부르던 자장가를 하나씩 확인했다. 어느 순간 원본이 물었다. ‘그럼 우리 중 누가 진짜야?’ 화면 속 윤서진은 아주 늦게 대답했다. ‘둘 다 살아남은 거 아닐까.’","그날의 공식 기록에는 생존자가 한 명이라고 적혔다. 그러나 당신이 보관한 마지막 사진에는 병실 창문을 바라보는 윤서진과, 유리창에 비친 단말기의 초록빛 얼굴이 나란히 남아 있다."],quote:"나를 대신하지 마. 나도 너를 지우지 않을게. 우리 둘 다 다음 날로 가자.",after:"두 윤서진은 서로 다른 이름으로 살았고, 해마다 그 병실에서 단 한 번 만났다."}
};

export default function Home(){
 const [phase,setPhase]=useState<"intro"|"boot"|"prologue"|"game"|"recap"|"end">("intro"),[act,setAct]=useState(0),[showTitle,setShowTitle]=useState(true),[open,setOpen]=useState<number|null>(null),[done,setDone]=useState<boolean[][]>([[false,false,false],[false,false,false],[false,false,false]]),[choices,setChoices]=useState<Choice[]>([]),[recap,setRecap]=useState(0),[archive,setArchive]=useState(false),[ending,setEnding]=useState("truth");
 useEffect(()=>{if(phase==="boot"){const t=setTimeout(()=>setPhase("prologue"),1800);return()=>clearTimeout(t)}},[phase]);
 useEffect(()=>{if(phase==="game"&&showTitle){const t=setTimeout(()=>setShowTitle(false),5200);return()=>clearTimeout(t)}},[phase,act,showTitle]);
 const solve=(i:number)=>setDone(d=>d.map((row,a)=>a===act?row.map((v,n)=>n===i?true:v):row));
 const choose=(c:Choice)=>{const next=[...choices,c];setChoices(next);if(act<2){setRecap(act);setArchive(false);setPhase("recap")}else{const counts={truth:0,life:0,mirror:0};next.forEach(x=>counts[x]++);const max=Math.max(...Object.values(counts));const tied=Object.values(counts).filter(x=>x===max).length>1;setEnding(tied?"hidden":counts.truth===max?"truth":counts.life===max?"life":"mirror");setPhase("end")}};
 const nextAct=()=>{setAct(recap+1);setShowTitle(true);setOpen(null);setPhase("game")};
 if(phase==="intro")return <main className="intro"><img src="/b3-intro.png" alt="지하 3층"/><div className="intro-vignette"/><div className="intro-action"><p>HANBIT ELECTRONICS · ARCHIVE 03-17</p><button onClick={()=>setPhase("boot")}>▶ 시작하기</button><small>기록은 설명하지 않는다. 연결만 남긴다.</small></div></main>;
 if(phase==="boot")return <main className="boot"><div className="boot-logo">HANBIT<span>98</span></div><p>손상된 볼륨을 마운트하는 중...</p><div className="bootbar"><i/></div></main>;
 if(phase==="prologue")return <main className="prologue"><article><small>2000년 3월 17일 · 한빛전자 구사옥</small><h1>사라진 사람의 이름</h1><p>당신은 폐업한 회사의 문서와 저장장치를 분류하는 외부 기록물 조사원이다. 특허 분쟁에 대비해 보존할 자료와 파쇄할 자료를 나누는 일. 한빛전자는 이번 달에 맡은 네 번째 현장이었다. 적어도 사원 명단에서 <b>윤서진</b>이라는 이름을 보기 전까지는.</p><p>윤서진은 오래전 당신의 친구였고, 한때는 연인이었다. 함께 새벽 첫차를 기다리고, 서로가 싫어하는 커피를 외우고, 언젠가 바다가 보이는 도시에서 살자고 말했던 사람. 한빛전자 연구소에 들어간 뒤 연락은 뜸해졌지만 마지막 통화까지는 평범했다. “큰 실험이 끝나면 만나자.” 다음 날부터 전화는 끊겼다.</p><p>회사는 그녀가 해외 연구소로 자진 출국했다고 말했다. 가족도 같은 통보를 받았다. 주소도 연락처도 없었다. 당신은 기다렸고, 화를 냈고, 결국 자신만 버려졌다고 믿는 편을 택했다. 그렇게 여덟 달 동안 윤서진 없는 일상에 익숙해졌다.</p><p>작업 마지막 날, 철거반장이 도면과 맞지 않는 전력 사용량을 보여줬다. 폐쇄된 건물에서 매일 밤 23시 07분마다 3분 동안 전기가 빠져나가고 있었다. 배선을 따라가자 존재하지 않는 엘리베이터 문과, 여덟 달 전 새로 발라진 콘크리트 벽이 나왔다.</p><p>벽 안에는 회사 자산 번호가 붙은 PC와 전화선, 계속 돌아가는 냉각팬이 있었다. 봉인 스티커에는 <b>자료보존실 03-17</b>. 사용자 카드에는 <b>윤서진 / 연구원 / 퇴사 처리</b>. 그러나 인사 이관 목록에서 그녀의 퇴직 서류만 비어 있었다.</p><p>그제야 마지막 통화가 다르게 들렸다. 그녀는 “실험이 끝나면”이 아니라 “내가 끝나면”이라고 말했던 것 같았다. 너무 오래된 기억이라 확신할 수 없었다.</p><blockquote>모니터 아래 카세트 라벨에는 당신이 기억하는 그녀의 필체가 남아 있다.<br/>“나를 찾지 말고, 내가 왜 둘이 되었는지 찾아줘. 그리고 네가 기억하는 나를 정답이라고 믿지 마. — 서진”</blockquote><p>내일 아침이면 건물은 철거된다. 전원을 켜면 애써 묻어둔 여덟 달도 다시 시작될 것이다. 하지만 지금 돌아서면, 그녀가 떠난 것인지 사라진 것인지 영원히 알 수 없다.</p><button onClick={()=>setPhase("game")}>PC의 전원을 켠다</button></article></main>;
 if(phase==="recap")return <Recap act={recap} choice={choices[recap]} archive={archive} close={()=>setPhase("game")} next={nextAct}/>;
 if(phase==="end"){const e=ENDS[ending];return <main className={`hard-ending end-${ending}`} style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.18),rgba(0,0,0,.82)),url(/ending-${ending}.png)`}}><div className="ending-door"><b>B3</b><i/></div><article><small>PROJECT MIRROR · ENDING</small><time>{e.date}</time><h1>{e.title}</h1>{e.paragraphs.map((p,i)=><p key={i}>{p}</p>)}<blockquote>“{e.quote}”</blockquote><footer>{e.after}</footer><div className="ending-path">당신이 남긴 흔적 {choices.map((c,i)=><span key={i}>{c==="truth"?"기록":c==="life"?"맥박":"복제"}</span>)}</div><button onClick={()=>location.reload()}>1999년 7월 17일로 돌아가기</button></article></main>}
 const a=ACTS[act];return <main className="mystery-desktop">{showTitle&&<div className="act-title-card detailed"><div><small>PROJECT MIRROR · CHAPTER {act+1}</small><h1>{a.title}</h1><p>{a.place}</p><div className="act-story">{ACT_STORY[act].map((p,i)=><p key={i}>{p}</p>)}</div></div></div>}<header><b>HANBIT 98</b><span>{a.title}</span><em>ACT {act+1}/3</em></header><nav className="mystery-icons">{a.files.map((f,i)=><button key={f} className={done[act][i]?"done":""} onClick={()=>setOpen(i)}><i>{done[act][i]?"✓":a.icons[i]}</i>{f}</button>)}<button className="core" onClick={()=>setOpen(3)}><i>🔓</i>{a.core}</button></nav><aside className="case-note"><h3>수사 기록</h3>{ACTS.map((x,i)=><p key={x.title} className={i<act?"done":i===act?"now":""}><b>{i<act?"완료":i===act?"진행":"잠김"}</b>{i<=act?x.title:"기밀 기록"}</p>)}{act>0&&<button onClick={()=>setOpen(4)}>증거 보관함</button>}{choices.slice(0,act).map((_,i)=><button key={i} onClick={()=>{setRecap(i);setArchive(true);setPhase("recap")}}>지난 기록 {i+1}</button>)}</aside>{open!==null&&<Window title={open===4?"증거 보관함":open===3?a.core:a.files[open]} close={()=>setOpen(null)}>{open===4?<EvidenceArchive act={act}/>:open===3?<Core act={act} done={done[act]} choose={choose}/>:<Puzzle act={act} index={open} solved={done[act][open]} solve={()=>solve(open)} allDone={done[act]}/>}</Window>}<footer><button>▣ 시작</button><span>탐색 중 · 정해진 순서는 없습니다</span><time>00:{String(3+act*17).padStart(2,"0")}</time></footer></main>
}

function Window({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <section className="mystery-window"><div className="window-head"><b>{title}</b><button onClick={close}>×</button></div><div className="window-content">{children}</div></section>}
function EvidenceArchive({act}:{act:number}){return <div className="evidence-archive"><h2>확보된 원본</h2><p>정리되지 않은 자료가 수집된 순서대로 보관되어 있다.</p><section><img src="/b3-film.png" alt="B3 손상 필름"/><article><p>22:41 · ■ ● ▲</p><p>BLUE / AMBER / RED</p><blockquote>“나는 어느 쪽이지?”</blockquote></article></section><section><article><p>최민호: 이름 말고 이니셜과 사번.</p><p>최민호: 검증은 사번 두 자리와 차단 시각 네 자리를 전부 더해.</p><p>김주현: 제어실 색 잠금은 필름 가장자리에 찍어뒀어. 도형은 색의 순서만 가리켜.</p></article></section>{act>1&&<section><img src="/b3-cctv.png" alt="봉합된 CCTV"/><article><p>22:58 · A / C / D</p><blockquote>“기억은 복사되지만 사람은 복사되지 않는다.”</blockquote></article></section>}</div>}

function Puzzle({act,index,solved,solve,allDone}:{act:number;index:number;solved:boolean;solve:()=>void;allDone:boolean[]}){
 if(act===0&&index===0)return <Files solved={solved} solve={solve}/>;
 if(act===0&&index===1)return <Photo solved={solved} solve={solve}/>;
 if(act===0)return <Chat solved={solved} solve={solve} photo={allDone[1]}/>;
 if(act===1&&index===0)return <Cctv solved={solved} solve={solve}/>;
 if(act===1&&index===1)return <Power solved={solved} solve={solve} cctv={allDone[0]}/>;
 if(act===1)return <Audio solved={solved} solve={solve} powered={allDone[1]}/>;
 if(act===2&&index===0)return <Memory solved={solved} solve={solve}/>;
 if(act===2&&index===1)return <Witness solved={solved} solve={solve} memory={allDone[0]}/>;
 return <Glyph solved={solved} solve={solve} witness={allDone[1]}/>;
}

function Files({solved,solve}:{solved:boolean;solve:()=>void}){const [seen,setSeen]=useState<string[]>([]),[order,setOrder]=useState<string[]>([]),[bad,setBad]=useState(false);const open=(x:string)=>setSeen(s=>s.includes(x)?s:[...s,x]);const pick=(x:string)=>{const n=[...order,x];if(n.length===3){if(n.join()==="roster,minutes,log"){solve();setBad(false)}else{setOrder([]);setBad(true)}}else setOrder(n)};return <div className="file-puzzle"><div className="tree"><button onClick={()=>open("minutes")}>▸ 이사회_회의.tmp</button><button onClick={()=>open("roster")}>▸ 개인폴더_043</button><button onClick={()=>open("log")}>▸ 폐쇄후_복구.chk</button></div><article>{seen.includes("minutes")&&<p><b>07/16 18:20 · 최민호 주임 발신</b><br/>김 기사님, 요청하신 현상실 장비 인수증은 별관 2층 데이터실 두 번째 방, 80번 서류함에 넣었습니다. 오늘 촬영분까지 처리되면 B3 필름은 전부 회수하세요.<br/><br/>추신: 윤 연구원에게 원본 폐기 조항은 아직 말하지 마십시오.</p>}{seen.includes("roster")&&<p><b>07/15 21:06 · 윤서진 개인 메모</b><br/>화면 속 아이가 먼저 내 꿈 이야기를 했다. 내가 말하지 않은 기억인데.<br/><br/>김 기사에게 맡긴 열쇠는 본관 지하 기록실 67번 보관함에 두었다. 내일 아침 필름과 같이 찾을 것. 열쇠고리에는 ‘어두운 쪽부터’라고 적혀 있다.</p>}{seen.includes("log")&&<p><b>07/17 03:11 · 박상무 발신</b><br/>B3의 필름과 암실 비품을 모두 폐기하십시오. 김주현이 쓰던 교정지는 발견 즉시 파쇄하고, 지하 기록실과 별관 데이터실을 먼저 확인할 것.<br/><br/>보고서에는 윤서진이 16일 밤 자진 퇴사한 것으로 기재합니다.</p>}{seen.length===0&&<p className="noise-text">세 파일의 생성 시각이 손상됐다. 본문에 남은 날짜는 서로 다르다.</p>}{seen.length===3&&!solved&&<div className="sector-puzzle"><small>복구 프로그램은 세 섹터를 한 번씩만 읽는다.</small><div>{["log","minutes","roster"].map(x=><button disabled={order.includes(x)} key={x} onClick={()=>pick(x)}>{x==="log"?"폐쇄 후":x==="minutes"?"회의 당일":"전날 메모"}</button>)}</div><p>{order.map(x=>x==="log"?"폐쇄 후":x==="minutes"?"회의 당일":"전날 메모").join(" → ")||"…"}</p>{bad&&<b className="error">SECTOR ORDER INVALID</b>}</div>}{solved&&<div className="recovered-note"><b>삭제되지 않은 김주현의 답장</b><blockquote>“서진 씨, 사진은 거짓말을 안 해요. 사람이 지우려고 할 뿐이지. 물건은 말한 두 곳에 나눠 뒀습니다. 어두운 쪽을 먼저 보세요.”</blockquote></div>}</article></div>}
function Photo({solved,solve}:{solved:boolean;solve:()=>void}){const [light,setLight]=useState(20),[contrast,setContrast]=useState(20);const clear=light===67&&contrast===80;return <div className="photo-puzzle"><div className="dark-photo generated-film" style={{filter:`brightness(${light/67}) contrast(${contrast/80})`}}><img src="/b3-film.png" alt="손상된 B3 필름"/>{clear&&<span>22:41 · ■ ● ▲<br/>BLUE / AMBER / RED</span>}</div><label>노출 <input type="range" min="1" max="100" value={light} onChange={e=>setLight(+e.target.value)}/><output>{light}</output></label><label>대비 <input type="range" min="1" max="100" value={contrast} onChange={e=>setContrast(+e.target.value)}/><output>{contrast}</output></label>{clear&&!solved&&<button onClick={solve}>필름 고정</button>}{solved&&<div className="recovered-note"><b>필름 가장자리</b><p>22:41 · ■ ● ▲ · BLUE / AMBER / RED</p><blockquote>사진 속 캡슐 유리에 손가락으로 쓴 문장: “나는 어느 쪽이지?”</blockquote></div>}</div>}
function Chat({solved,solve,photo}:{solved:boolean;solve:()=>void;photo:boolean}){const [pass,setPass]=useState(""),[err,setErr]=useState(false);return <div className="chat-puzzle">{!photo&&<p className="noise-text">보관함 헤더에 네 자리 값이 요구된다. 암호 설명은 없다.</p>}<input maxLength={4} value={pass} onChange={e=>setPass(e.target.value.replace(/\D/g,""))}/><button onClick={()=>{if(pass==="2241"){solve();setErr(false)}else setErr(true)}}>ARCHIVE MOUNT</button>{err&&<p className="error">HEADER MISMATCH</p>}{solved&&<div className="log"><p>22:39 김주현: 반납표 계정은 최민호 CMH-112, 나는 KJH-067로 찍혀. 서진 씨 것도 같은 방식이야.</p><p>22:42 최민호: 이름 말고 이니셜과 사번. 윤 연구원 개인폴더 번호는 그대로 붙이면 돼.</p><p>22:51 최민호: 검증은 사번 두 자리와 차단 시각 네 자리를 전부 더해.</p><p>22:57 최민호: 콘솔은 늘 같은 순서야. 접속자, 사고일, 전원이 죽은 시각, 마지막 검산.</p><p>23:02 김주현: 제어실 색 잠금은 필름 가장자리에 찍어뒀어. 도형은 색의 순서만 가리켜.</p><p>23:06 윤서진: 밖에 누가 있다면 기록을 지우지 말아줘.</p></div>}</div>}

function Cctv({solved,solve}:{solved:boolean;solve:()=>void}){const [d,setD]=useState([0,0,0]);const ok=d.join()==="2,3,1";return <div className="dial-puzzle"><p className="noise-text">RECOVERED NOTE: “세 눈이 붉은 등을 함께 보았을 때, 화살표가 남긴 길만 살아 있었다.”</p><div>{d.map((v,i)=><button key={i} onClick={()=>setD(x=>x.map((n,j)=>j===i?(n+1)%4:n))}>CAM {String.fromCharCode(65+i)}<i style={{transform:`rotate(${v*90}deg)`}}>➤</i><small>{["22:54","22:58","23:02","23:06"][(v+i)%4]}</small></button>)}</div>{ok&&!solved&&<button onClick={solve}>프레임 봉합</button>}{solved&&<div className="recovered-note"><img className="evidence-image" src="/b3-cctv.png" alt="봉합된 세 개의 CCTV 화면"/><b>세 화면이 겹친 프레임</b><p>22:58 · A / C / D</p><blockquote>화면 끝에서 윤서진이 카메라를 올려다본다. 아직 전원 차단 전이다.</blockquote></div>}</div>}
function Power({solved,solve,cctv}:{solved:boolean;solve:()=>void;cctv:boolean}){const [on,setOn]=useState([false,false,false,false]);const ok=on.join()==="true,false,true,true";return <div className="power-puzzle"><p className="noise-text">B 선로 퓨즈에는 검게 탄 손자국이 남아 있다. 패널에는 설명서가 없다.</p><div>{on.map((v,i)=><button className={v?"on":""} key={i} onClick={()=>setOn(a=>a.map((x,j)=>i===j?!x:x))}>{String.fromCharCode(65+i)}<i/></button>)}</div>{cctv&&<small>카메라를 봉합한 뒤부터 A·C·D 램프에만 약한 잔광이 보인다.</small>}<button disabled={!ok} onClick={solve}>보조 전력 투입</button>{solved&&<div className="recovered-note"><b>AUDIO BUS ONLINE</b><blockquote>생명유지 장치가 7A를 가져갔다. 남은 전력이 오래된 테이프 한 개를 돌린다.</blockquote></div>}</div>}
function Audio({solved,solve,powered}:{solved:boolean;solve:()=>void;powered:boolean}){const [parts,setParts]=useState(["복사되지만","사람은","복사되지 않는다","기억은"]);const move=(i:number)=>setParts(p=>{const n=[...p];[n[i],n[(i+1)%4]]=[n[(i+1)%4],n[i]];return n});const ok=parts.join(" ")==="기억은 복사되지만 사람은 복사되지 않는다";return <div className="audio-puzzle"><p className="wave">▁▂▆█▃▁ ▂▇█▅▂ ▁▃▇█▂</p>{!powered&&<p className="noise-text">전압 부족 — 입 모양과 목소리가 서로 다른 위치에서 끊긴다.</p>}<div>{parts.map((x,i)=><button key={x} onClick={()=>move(i)}>{x} ↔</button>)}</div><small>케이스에는 “말이 되는 문장을 믿지 말고, 서진이 숨을 쉬는 자리를 찾아라”라는 낙서만 남아 있다.</small>{ok&&powered&&!solved&&<button onClick={solve}>테이프 이어 붙이기</button>}{solved&&<div className="recovered-note"><blockquote>“기억은 복사되지만 사람은 복사되지 않는다. 그런데 화면 속 아이는 내가 잊은 것을 기억한다.” — 윤서진</blockquote></div>}</div>}

function Memory({solved,solve}:{solved:boolean;solve:()=>void}){const [cards,setCards]=useState([1,4,2,3]);const labels:Record<number,string>={1:"23:07 · 천장의 불이 꺼졌다",2:"07/15 · 내 이름 아래 서명했다",3:"23:04 · 화면 속 내가 눈을 떴다",4:"23:18 · 전화기 너머로 세 번 불렀다"};const swap=(i:number)=>setCards(c=>{const n=[...c];[n[i],n[(i+1)%4]]=[n[(i+1)%4],n[i]];return n});const ok=cards.join()==="2,3,1,4";return <div className="memory-puzzle"><p className="noise-text">네 장면은 모두 윤서진의 눈으로 저장됐다. 날짜와 시계만 손상되지 않았다.</p>{cards.map((c,i)=><button key={c} onClick={()=>swap(i)}><b>0{c}</b>{labels[c]} ↔</button>)}{ok&&!solved&&<button onClick={solve}>연속 기억으로 고정</button>}{solved&&<div className="recovered-note"><img className="evidence-image" src="/mirror-memory.png" alt="캡슐의 윤서진과 화면 속 윤서진"/><blockquote>마지막 전화에서 윤서진은 “그 아이를 끄지 마세요”라고 말했다.</blockquote></div>}</div>}
function Witness({solved,solve,memory}:{solved:boolean;solve:()=>void;memory:boolean}){const [pick,setPick]=useState("");return <div className="witness-puzzle"><button className={pick==="kim"?"picked":""} onClick={()=>setPick("kim")}><b>김주현</b> “23:00에 실험실을 떠났다.”<small>카드 로그: 23:09 퇴실</small></button><button className={pick==="choi"?"picked":""} onClick={()=>setPick("choi")}><b>최민호</b> “차단 뒤 B3에 들어갔다.”<small>카드 로그: 23:12 입실</small></button>{memory&&<p>복원 기억에서 차단은 성공 통보 이후였다.</p>}<button disabled={pick!=="kim"} onClick={solve}>증언 봉인 해제</button>{solved&&<p className="evidence">직접 모순: 김 / 퇴실 분 09</p>}</div>}
function Glyph({solved,solve,witness}:{solved:boolean;solve:()=>void;witness:boolean}){const [r,setR]=useState([0,0,0,0]);const target=[1,2,0,3];const ok=r.join()===target.join();return <div className="glyph-puzzle"><p className="noise-text">시설팀 메일: “네 장의 기억판은 발생 순서대로 끼우면 됩니다. 모서리 숫자가 있는 방향이 위예요. 김 기사가 두 번째 판만 거울 뒤에 달아 두어서 또 뒤집었습니다.”</p><div>{r.map((x,i)=><button key={i} onClick={()=>setR(a=>a.map((v,j)=>i===j?(v+1)%4:v))}><i style={{transform:`rotate(${x*90}deg)`}}>◈</i></button>)}</div>{witness&&<small>김주현의 출입카드 뒷면에는 좌우가 뒤집힌 사내 로고가 붙어 있다.</small>}<button disabled={!ok} onClick={solve}>패턴 투사</button>{solved&&<div className="recovered-note"><blockquote>패턴 중앙에 B라는 글자가 떠오른다. 캡슐 라벨에는 A가 적혀 있다.</blockquote></div>}</div>}

function Core({act,done,choose}:{act:number;done:boolean[];choose:(c:Choice)=>void}){const [vals,setVals]=useState(["","","","" ]),[colors,setColors]=useState<string[]>([]),[err,setErr]=useState(false),[unlocked,setUnlocked]=useState(false);const set=(i:number,v:string)=>setVals(a=>a.map((x,n)=>n===i?v:x));if(act===0){const readable=done.filter(Boolean).length;return <div className="core-console"><pre>{readable<1?"SUBJECT: ███-███\nEVENT: ██/██\nOFFSET: ██:██\nSIGN: ██":readable<2?"SUBJECT: [ACCOUNT]\nEVENT: [THE DAY BEFORE SEAL]\nOFFSET: [MAIN-CUT]\nSIGN: digit sum":readable<3?"SUBJECT: [ACCOUNT]\nEVENT: MMDD\nOFFSET: HHMM\nSIGN: employee + cutoff digits":"SUBJECT / EVENT / OFFSET / SIGN"}</pre><div className="console-fields">{["SUBJECT","EVENT","OFFSET","SIGN"].map((x,i)=><label key={x}><span>{x}</span><input aria-label={x} value={vals[i]} onChange={e=>set(i,e.target.value.toUpperCase())}/></label>)}</div><button onClick={()=>{const ok=vals[0]==="YSJ-043"&&vals[1]==="0716"&&vals[2]==="2307"&&vals[3]==="19";setErr(!ok);if(ok)setUnlocked(true)}}>EXECUTE</button>{unlocked&&<div className="final-choices"><button onClick={()=>choose("truth")}>외부 회선에 복사한다</button><button onClick={()=>choose("life")}>B3 생명신호를 추적한다</button></div>}{err&&<p className="error">REJECTED — 입력값의 관계가 성립하지 않음</p>}</div>}
 if(act===1){const seq=["blue","amber","red"];return <div className="core-console"><pre>{done[0]?"FRAME 22:58 / ROUTE A-C-D":"FRAME ??:?? / ROUTE ?-?-?"}<br/>{done[1]?"LOAD 7A / CHANNEL AUDIO":"LOAD ?A / CHANNEL ????"}<br/>{done[2]?"REEL 3-1-2-4":"REEL ?-?-?-?"}</pre><div className="color-lock">{["red","blue","amber"].map(c=><button key={c} className={c} onClick={()=>setColors(s=>[...s,c].slice(-3))}/>)}</div><p>{colors.map(c=>c.toUpperCase()).join(" → ")||"COLOR SEQUENCE"}</p><button disabled={colors.join()!==seq.join()||!done.every(Boolean)} onClick={()=>choose("life")}>OPEN B3</button><button disabled={colors.join()!==seq.join()||!done.every(Boolean)} onClick={()=>choose("mirror")}>OPEN MIRROR</button></div>}
 const ready=vals[0].toUpperCase()==="2409B"&&done.every(Boolean);return <div className="core-console"><pre>{done[0]?"ORDER: 2·3·1·4":"ORDER: ?·?·?·?"}<br/>{done[1]?"CONTRADICTION: K / 09":"CONTRADICTION: ? / ??"}<br/>{done[2]?"OWNER: B":"OWNER: ?"}</pre><input aria-label="복원 키" value={vals[0]} onChange={e=>set(0,e.target.value)}/><div className="final-choices"><button disabled={!ready} onClick={()=>choose("truth")}>모든 기록을 전송한다</button><button disabled={!ready} onClick={()=>choose("life")}>캡슐 A를 연다</button><button disabled={!ready} onClick={()=>choose("mirror")}>신호 B의 제한을 해제한다</button></div></div>}

function Recap({act,choice,archive,close,next}:{act:number;choice:Choice;archive:boolean;close:()=>void;next:()=>void}){return <main className="recap-screen"><article><small>PROJECT MIRROR · ARCHIVE {act+1}</small><h1>지난 이야기</h1><h2>{ACTS[act].title}</h2><p>{act===0?"회의실 백업, 필름 가장자리, 메신저 기록은 서로 다른 조각처럼 보였지만 하나의 밤을 가리켰다. 윤서진은 23시 07분 이후 기록에서 사라졌다.":"서로 어긋난 카메라와 끊어진 배전을 맞추자 두 신호가 나타났다. 하나는 캡슐의 맥박, 다른 하나는 서버에서 당신을 부르는 목소리였다."}</p><p>당신은 <b>{choice==="truth"?"기록을 밖으로 보냈다":choice==="life"?"맥박이 있는 쪽을 열었다":"복제 신호에 통로를 만들었다"}</b>.</p><button onClick={archive?close:next}>{archive?"돌아가기":`${act+2}막 시작`}</button></article></main>}
